# Generated by Django 4.2.1 on 2023-05-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnose',
            name='title',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
